Feature/multitexturing
OpenSpace/Ghoul pull request #59
Opened 2021-02-03 09:42 UTC by Roxeena

Improved model loading that supports models with multiple parts, materials and textures.

2021-02-04 10:31 UTC, alexanderbock requested changes
Overall it looks good :)

We should have an additional look at modelreaderassimp.cpp:380 et cetera after the cleanup to see if those if/else statements can be compressed a bit more

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +        ModelMesh loadedMesh = processMesh(mesh, scene, globalTransform, textureStorage, modelDirectory);
These parameters would be split up into multiple lines:
```
ModelMesh loadedMesh = processMesh(
    mesh,
    scene,
    globalTransform,
    textureStorage,
    modelDirectory
);
```

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +        processNode(node->mChildren[i],
The `node->mChildren[i]` would go on its own line, too

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +    return std::make_unique<modelgeometry::ModelGeometry>(
This does an unncessary move and could just be:
```
return std::make_unique<modelgeometry::ModelGeometry>(std::move(meshArray), std::move(textureStorage));

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +    case opengl::Texture::Format::Red:
We indent the `case` label by 4 characters:
```cpp
switch (format) {
    case opengl::Texture::Format::Red:
    case opengl::Texture::Format::RG:
    ...
    
}
```

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +    formatString.replace(0, subString.length(), subString);
You could just return "Red ", "RG  ", "RGB ", "BGR " etc directly without the need for the character manipulations?

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +std::string formatToString(opengl::Texture::Format format) {
Since the format length is fixed, you could instead return a `std::array<const char, 4>` to make the compiler help us ensure that we can't put longer strings in there

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +std::string dataTypeToString(const GLenum dataType) {
Same here as above

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +    if (format == "Red ") {
In these kind of instances, where there are a lot of `if`, `if else` statements, I prefer to relax the "one line per statement" rule and write instead:
```cpp
if (format == "Red ") { return opengl::Texture::Format::Red; }
else if (format == "RG  ") { return openspace::Texture::format::RG; }
....
```
as it makes it a bit more readable and shorter

```

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +    if (dataType == "byte") {
See above

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +GLenum stringToDataType(const std::string dataType) {
Instead of a `const std::string`, this can be a `std::string_view` as you are only looking at the text, not needing to make a copy

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +opengl::Texture::Format stringToFormat(const std::string format) {
Instead of a `const std::string`, this can be a `std::string_view` as you are only looking at the text, not needing to make a copy

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +std::string dataTypeToString(const GLenum dataType) {
No need to define the `dataType` as `const`

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +            throw ModelLoadException(
This all fits on the same line:
`throw ModelLoadException(cachedFile, "No texture size was loaded", this);`

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +        textureEntry.texture->setPixelData(data);
Even though it is covered by the default argument, I'd like to see the `opengl::Texture::TakeOwnership::Yes` as the second argument to make it clear to the user that we are passing the ownership of the data into the texture class and not leak it

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +        fileStream.read(reinterpret_cast<char*>(&dimensions.x), sizeof(int32_t));
I don't think this is necessarily correct;  `glm;:uvec3` has `unsigned int` as an underlying datatype which a) is not the same as `int32_t` and it's not even guaranteed to be 32 bit in all circumstances.  Better to declare:
```cpp
std::array<int32_t, 3> dimensionStorage;
fileStream.read(reinterpret_cast<char*>(dimensions.data()), 3 * sizeof(int32_t));
glm::uvec3 dimensions = glm::uvec3(static_cast<unsigned int>(dimensionStorage[0]), static_cast<unsigned int>(dimensionStorage[1]), static_cast<unsigned int>(dimensionStorage[2]));
```

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +            unsigned int index;
`sizeof(unsigned int` is not defined and it might change.. better to use `uint32_t` here

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +            fileStream.read(reinterpret_cast<char*>(
The `reinterpret_cast<char*>(` belongs to the `&texture.useForceColor` argument and would go on the next line:
```cpp
fileStream.read(
    reinterpret_cast<char*>(&texture.useForcedColor),
    sizeof(bool)
);
```

Also consider writing this as a `uint8_t` instead.  Technically, `sizeof(bool)` can be any value depending on the compiler (https://eel.is/c++draft/expr.sizeof#footnote-65)

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +                unsigned int index;
=> `uint32_t`

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +        meshArray.push_back(std::move(ModelMesh(
No need for the `std::move` here, since the `ModelMesh` is a temporary object, so it can be automatically moved from. So:
```cpp
        meshArray.push_back(
            ModelMesh(
                std::move(vertexArray),
                std::move(indexArray),
                std::move(textureArray)
            )
        );
```
is just fine

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +        std::move(modelgeometry::ModelGeometry(
Same here;  temporary object will be automatically moved from

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +                                       const modelgeometry::ModelGeometry* model) const
This function will crash anyway if someone passes in a `nullptr`, so better to define it as `const modelgeometry::ModelGeometry& model` instead

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +            &model->textureStorage()[te].texture->dimensions().x),
`dimensions` is a `glm::uvec3`, so it would be better to copy the values into an array of `uint32_t` values first and *then* serialize them out... just in case GLM changes their size types.  It's unlikely, but they are known for making subtle but breaking changes

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +        unsigned int internalFormat = static_cast<unsigned int>(
-> `uint32_t`

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +                sizeof(unsigned int)
Same here

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +                sizeof(unsigned int)
If you really don't want to copy the values into a separate array, you can put in a:
`static_assert(sizeof(unsigned int) == sizeof(uint32_t));` and we'll need to fix it if there is going to be a compiler that changes the size of `unsigned int`.  But at least then we'll get a compiler error

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +                sizeof(bool)
See `sizeof(bool)` discussion above.  Better:
```cpp
uint8_t h = model->meshes()[m]._textures[t].hasTexture) ? 1 : 0;

```

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +                sizeof(bool)
Same here

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +                    wasFound = std::strcmp(
Can do a check
```cpp
model->textureStorage()[te].name == model->meshes()[m]._textures[t].texture->name()
```
instead and skip the conversion to `const char*`

2021-02-04 10:31 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +                            sizeof(unsigned int)
Copy into `uint32_t` so that we are guaranteed the right number of bytes

2021-02-05 10:29 UTC, Roxeena commented on src/io/model/modelmesh.cpp
> +    if (isRenderableModel) {
The texture array will never be empty (if there is no textures the mesh is not rendered, if it is forced then a “dummy texture” is inserted to tell the shader to force the pink green material). But I can agree to move this part out into another function to make it clearer.

2021-02-05 10:33 UTC, Roxeena commented on src/io/model/modelmesh.cpp
> +                    program.setUniform("has_color_specular", false);
There can either be a specular color, a specular texture or nothing at all. If there is a specular texture the `"has_color_specular"` is set to false and `"has_texture_specular"` is set to true. If there is a specular color the `"has_texture_specular"` is set to false and the `"has_color_specular"` is set to true. But I see the problem that if it is rendered first with either a color or a texture and then without there will be a problem, I will look into it. :)

2021-02-05 10:35 UTC, Roxeena commented on src/io/model/modelreaderassimp.cpp
> +                textureArray.push_back(std::move(meshTexture));
They won't be executed after each other since `shouldSkip = true` on the next line.

2021-02-05 11:55 UTC, alexanderbock approved these changes

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelmesh.cpp
> +                    program.setUniform("has_color_specular", false);
In the worst case you can always just set the uniform to the base state in line 45 before the starting with this function.

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelmesh.cpp
> +
Extra empty line

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelmesh.cpp
> +{ }
Nitpicky;  extra space between braces

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +                          const aiTextureType type, const std::string& typeString,
`const` argument here is for the `aiTextureType`, too.   If it is a large parameter (> 8 bytes), it's better to pass it as a `const aiTextureType&`, otherwise just a `aiTextureType`

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +                textureArray.push_back(std::move(meshTexture));
Didn't see that;  you're right, of course

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +            if ((texture->mHeight == 0)) {
No need for the double parantheses

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +                    meshTexture.texture = nullptr;
How about replacing lines 125-129, 137-141, 150-154, 179-183 and 191- 195 with a single function call (which could be a local lambda, too:
```
auto generateDefaultTexture = [](ModelMesh::Texture texture) {
    texture.texture = nullptr;
    texture.hasTexture = false;
    texture.useForcedColor = true;
    texture.type = "color_diffuse";
    return texture;
};
```

Then all of the lines can be replaced with:
`textureArray.push_back(generateDefaultTexture(std::move(meshTexture)));`

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +ModelMesh processMesh(const aiMesh* mesh, const aiScene* scene,
The program will crash if the `mesh` or the `scene` are nullptr, so we can pass them as references instead and make the called eat the nullptr dereferencing instead

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +        vertex.location[3] = 1.0;
If we always set the alpha value to 1, could we only use a 3-component vertex position?

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +        vertex.location[0] = mesh->mVertices[i].x;
Didn't pick up on that before, but it might better to rename `location` -> `position`.  Since "location" can also meed the location of a uniform in a shader... so we would have to write `locationLocation` which seems a bit weird

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +            // Each vertex can have at most 8 different texture coordinates.
Great comment :+1:

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +    unsigned int nIndices = (mesh->mNumFaces) * static_cast<unsigned int>(3);
- no need for the parantheses around `mesh->mNumFaces`
 - no need for the static cast, you can write `3u` for an unsigned int literal if that is definitely necessary (which I'm not sure of)

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +    // We assume a convention for sampler names in the shaders. Each diffuse texture
Nice

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +    if (hasOpacity == AI_SUCCESS) {
Can combine the two `if` statements into one:
`if (hasOpacity == AI_SUCCESS && opacity == 0.f) {`

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +            if (color4.a != 0) {
If color4.a is a float, it should be compared to `0.f` to make that clear from the reading.. if it is a `double`, use `0.0`

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +            if (color4.a != 0) {
Same here

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +void processNode(const aiNode* node, const aiScene* scene, std::vector<ModelMesh>& meshes,
- See above regarding `const aiNode*` -> `const aiNode&` and same for `aiScene`
 - No need to reclare the `forceRenderInvisible` and `notifiyInvisibleDropped` as `const bool` as it does the same as `bool`

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +                                                 const bool notifyInvisibleDropped) const
Same as above regarding `const bool` -> `bool`

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +            break;
No need for the `break;`s here as the function returns before anyway ..  That will allow you to move the returns onto the same line as the case label too to reduce the line count and make it look neater

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +    std::string formatString;
The `formatString` and `subString` variables are no longer needed

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +    std::string formatString;
Same as above

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +            break;
Same as above

2021-02-05 11:55 UTC, alexanderbock commented on src/io/model/modelreaderassimp.cpp
> +        fileStream.write(reinterpret_cast<const char*>(
I'd move the `reinterpret_cast` down to the same line as the `dimensionStorage` as it is more directly related to that:
```
        fileStream.write(
            reinterpret_cast<const char*>(dimensionStorage.data()),
            3 * sizeof(int32_t)
        );
```

2021-02-05 13:37 UTC, Roxeena commented on src/io/model/modelmesh.cpp
> +        if (_textures[i].type == "texture_diffuse" ||
In the render function I use some string manipulation so an enum might not work but maybe a `constexpr const char*` instead?

2021-02-08 11:03 UTC, Roxeena commented on src/io/model/modelmesh.cpp
> +    if (isRenderableModel) {
I tried this and it broke the texture binding, I realized it was because of the line `glActiveTexture(GL_TEXTURE0 + textureCounter)`. Since it was moved out into its own function that would run over all meshes before the rendering, the activated texture would not be right.

2021-03-02 14:59 UTC, merged

2021-03-03 08:46 UTC, alexanderbock commented
Wheeeee!